# Generated by Django 5.2.17 on 2026-09-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('UserID', models.IntegerField(blank=True, db_index=True, null=True)),
                ('OrderDate', models.DateTimeField(blank=True, null=True)),
                ('DeliveryDate', models.DateTimeField(blank=True, null=True)),
                ('TotalAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Products',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(blank=True, max_length=255, null=True)),
                ('LastName', models.CharField(blank=True, max_length=255, null=True)),
                ('Email', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('Password', models.CharField(blank=True, max_length=255, null=True)),
                ('PhoneNumber', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
